### ISSUE TITLE
[Documentation] What is displayIO?

### ISSUE THREAD

**Issue by github-throwaway** [adafruit/Adafruit_CircuitPython_DisplayIO_SSD1306#16]
This might be a dumb question but what *is* displayIO? How is this library different from the [framebuf version](https://github.com/adafruit/Adafruit_CircuitPython_SSD1306)? I feel this difference should be explained in the documentation / readme.

**Comment by FoamyGuy** [comment]
See the guide here for usage and high level info about displayio: https://learn.adafruit.com/circuitpython-display-support-using-displayio/introduction

displayio is a display API that uses TileGrid, Group, Bitmap, and a few other objects to draw things on the screen.
