### ISSUE TITLE
Could not install packages due to an EnvironmentError: 404 Client Error:

### ISSUE THREAD

**Issue by DartLazer** [adafruit/Adafruit_CircuitPython_DisplayIO_SSD1306#18]
When trying to install by using pip3 as per instructions im getting the following error:

``Could not install packages due to an EnvironmentError: 404 Client Error: Not Found for url: https://pypi.org/simple/adafruit-circuitpython-displayio-ssd1306/``

**Comment by evaherrada** [comment]
@DartLazer Looks like it isn't currently available on PyPI. Not sure if or when it will be. In the meantime, try this https://github.com/adafruit/adafruit_circuitpython_ssd1306

**Comment by DartLazer** [comment]
Thanks!

**Comment by tannewt** [comment]
@dherrada could you please figure out how to get it on pypi? Thanks!

**Comment by evaherrada** [comment]
@tannewt Sure! (probably won't get to it until early next week but I'll add it to my list)
