### ISSUE TITLE
Where to find status of this library and its publication?

### ISSUE THREAD

**Issue by gvankeerberghen** [adafruit/Adafruit_CircuitPython_DisplayIO_SSD1306#7]
Hi, I arrived here looking for a module to show text on a 128x32 SPI OLED that I connected to my Raspberry Pi.

I saw the note in the install section of the Readme, still tried 
```sh
pip3 install adafruit-circuitpython-displayio-ssd1306
```
thinking that the note might have been outdated but no it doesn't exist on PyPi as far as I could see.

So I was wondering, 
- Is there a place to know the status regarding a PyPi publication?
- Is this already usable with Blinka via a manual install or is the whole code here a Work In Progress not intended for users yet?

Many thanks

**Comment by ladyada** [comment]
displayio version is not supported on pi

follow this guide https://learn.adafruit.com/monochrome-oled-breakouts/python-wiring
